
#define PERIODIC_TIME_CONTROL 1000 // 実行周期　μs
#define PERIODIC_TIME_LOG 10000 // 実行周期　μs

#define MOTOR_INPUT_LIMIT_VOLTAGE 8.0
#define MOTOR_DAC_CHANNEL 1

#define BRAKE_INPUT_LIMIT_VOLTAGE 5.0
#define BRAKE_DAC_CHANNEL 2